/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Kalo(props) {
  const { nodes, materials } = useGLTF("Kalo/kalo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials["Material.001"]}
        position={[-0.38, 1.07, 0.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Material.002"]}
        position={[-1.67, 5.08, 1]}
        rotation={[0.04, 0.08, 0.43]}
        scale={[1.77, 2.53, 1.77]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.002"]}
        position={[0.68, 3.33, 1.6]}
        rotation={[-1.62, -1.35, -1.31]}
        scale={[1.53, 2.19, 1.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["Material.003"]}
        position={[-1.08, 2.43, 0.82]}
        rotation={[-2.59, 1.15, 2.94]}
        scale={[0.11, 0.16, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={materials["Material.003"]}
        position={[-1.11, 2.46, 0.89]}
        rotation={[-2.87, 0.62, -2.95]}
        scale={[0.06, 0.09, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh.geometry}
        material={materials["Material.001"]}
        position={[-0.38, 0.19, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mball001.geometry}
        material={materials["Material.001"]}
        position={[-0.86, 2.12, 0.86]}
        rotation={[0, 0, 2.07]}
        scale={0.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kalo_straight001.geometry}
        material={materials["kalo straight"]}
        position={[3.15, 4.49, 2.72]}
        rotation={[1.52, 0.29, -0.79]}
        scale={0.7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kalo_straight002.geometry}
        material={materials["kalo straight"]}
        position={[0.05, 3.76, 1.2]}
        rotation={[-1.34, 0.19, 2.96]}
        scale={3.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kalo_straight003.geometry}
        material={materials["kalo straight"]}
        position={[-1.28, 2.52, 0.81]}
        rotation={[1.51, -0.29, 1.97]}
        scale={0.05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kalo_straight004.geometry}
        material={materials["kalo straight"]}
        position={[-1.2, 2.51, 0.94]}
        rotation={[1.39, -0.24, 1.36]}
        scale={0.03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kalo.geometry}
        material={materials.kalo}
        position={[-4.21, 6.42, 1.42]}
        rotation={[1.43, -0.16, 0.86]}
        scale={5.48}
      />
    </group>
  );
}

useGLTF.preload("/kalo.glb");
